name: Testsuite

on: [push, pull_request]

jobs:
  main:
    name: Run
    strategy:
      # Default, disable if you want to debug
      fail-fast: false
      matrix:
        # Latest stable version, update at will
        os: [ ubuntu-18.04, windows-2019 ]
        dc: [ dmd-latest] #, ldc-latest, dmd-master, ldc-master ]

    runs-on: ${{ matrix.os }}
    steps:

    # - name: '[Linux] Install dependencies'
    #   if: runner.os == 'Linux'
    #   run: |
    #     sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev netcat

    # Compiler to test with
    - name: Prepare compiler
      uses: mihails-strasuns/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2

    - name: '[POSIX] Build'
      if: runner.os != 'Windows'
      run: |
        - ls
        # - cd examples/sdl
        # - dub build --compiler=${DC}

    - name: '[Windows] Build'
      if: runner.os == 'Windows'
      run: |
        - dir
        # - cd examples/sdl
        # - dub build --compiler=%DC%
